-- 检查OrderDetail表结构
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH,
    DATA_PRECISION,
    DATA_SCALE,
    NULLABLE,
    DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'ORDERDETAIL'
ORDER BY COLUMN_ID;

-- 检查OrderDetail表的约束
SELECT 
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE,
    SEARCH_CONDITION
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME = 'ORDERDETAIL';

-- 检查外键约束
SELECT 
    a.CONSTRAINT_NAME,
    a.COLUMN_NAME,
    c_pk.TABLE_NAME as REFERENCED_TABLE,
    b.COLUMN_NAME as REFERENCED_COLUMN
FROM USER_CONS_COLUMNS a
JOIN USER_CONSTRAINTS c ON a.CONSTRAINT_NAME = c.CONSTRAINT_NAME
JOIN USER_CONSTRAINTS c_pk ON c.R_CONSTRAINT_NAME = c_pk.CONSTRAINT_NAME
JOIN USER_CONS_COLUMNS b ON c_pk.CONSTRAINT_NAME = b.CONSTRAINT_NAME
WHERE c.CONSTRAINT_TYPE = 'R'
AND a.TABLE_NAME = 'ORDERDETAIL';

-- 检查是否有现有的OrderDetail记录
SELECT COUNT(*) as Total_Records FROM PUB.OrderDetail;

-- 检查特定DishID=3的菜品信息
SELECT DishID, DishName, Price, IsAvailable, CategoryID FROM PUB.Dish WHERE DishID = 3;
