-- 检查数据库表结构的SQL脚本

-- 1. 检查STORE表的字段
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'STORE'
ORDER BY COLUMN_ID;

-- 2. 检查DEPARTMENT表的字段
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'DEPARTMENT'
ORDER BY COLUMN_ID;

-- 3. 检查STAFF表的字段
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'STAFF'
ORDER BY COLUMN_ID;

-- 4. 检查序列是否存在
SELECT SEQUENCE_NAME, LAST_NUMBER FROM USER_SEQUENCES 
WHERE SEQUENCE_NAME LIKE '%STAFF%';

-- 5. 测试简单查询
SELECT COUNT(*) as STORE_COUNT FROM PUB.STORE;
SELECT COUNT(*) as DEPARTMENT_COUNT FROM PUB.DEPARTMENT;
SELECT COUNT(*) as STAFF_COUNT FROM PUB.STAFF;
