-- 检查STAFFSCHEDULE表结构
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'STAFFSCHEDULE'
ORDER BY COLUMN_ID;

-- 查看表中的数据示例
SELECT * FROM PUB.STAFFSCHEDULE WHERE ROWNUM <= 5;
