ALTER TABLE Staff MODIFY STAFFID NUMBER GENERATED ALWAYS AS IDENTITY;
-- 1. 先删除可能存在的序列和触发器（如果存在）
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE PUB.STAFF_SEQ';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TRIGGER PUB.STAFF_BI_TRG';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN
         RAISE;
      END IF;
END;
/

-- 2. 创建员工表的序列（从当前最大ID+1开始）
DECLARE
   max_id NUMBER;
BEGIN
   SELECT NVL(MAX(STAFFID), 0) + 1 INTO max_id FROM PUB.STAFF;
   EXECUTE IMMEDIATE 'CREATE SEQUENCE PUB.STAFF_SEQ START WITH ' || max_id || ' INCREMENT BY 1 NOCACHE';
END;
/

-- 3. 验证序列是否创建成功
SELECT SEQUENCE_NAME, LAST_NUMBER FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'STAFF_SEQ';

-- 4. 测试序列是否正常工作
SELECT PUB.STAFF_SEQ.NEXTVAL AS NEXT_ID FROM DUAL;

-- 5. 查看当前序列值（这会消耗一个序列值）
SELECT PUB.STAFF_SEQ.CURRVAL AS CURRENT_ID FROM DUAL;
