-- 删除现有数据（如果需要重新测试）
-- DELETE FROM PUB.DISH;
-- DELETE FROM PUB.CATEGORY;

-- 插入菜品分类（只插入不存在的）
MERGE INTO PUB.CATEGORY c
USING (SELECT 1 as CATEGORYID, '热菜' as CATEGORYNAME, '各种热炒菜品' as DESCRIPTION, 1 as SORTORDER, 'Y' as ISACTIVE FROM dual
       UNION ALL SELECT 2, '凉菜', '各种凉拌菜品', 2, 'Y' FROM dual
       UNION ALL SELECT 3, '饮品', '各种饮料', 5, 'Y' FROM dual) s
ON (c.CATEGORYID = s.CATEGORYID)
WHEN NOT MATCHED THEN
  INSERT (CATEGORYID, CATEGORYNAME, DESCRIPTION, SORTORDER, ISACTIVE)
  VALUES (s.CATEGORYID, s.CATEGORYNAME, s.DESCRIPTION, s.SORTORDER, s.ISACTIVE);

-- 插入菜品数据（只插入不存在的）
MERGE INTO PUB.DISH d
USING (SELECT 1 as DISHID, 1 as STOREID, '宫保鸡丁' as DISHNAME, 28.00 as PRICE, 1 as CATEGORYID, 'Y' as ISAVAILABLE, '经典川菜，香辣可口' as DESCRIPTION, '' as IMAGEURL, 15 as ESTIMATEDTIME FROM dual
       UNION ALL SELECT 2, 1, '拍黄瓜', 12.00, 2, 'Y', '清爽开胃小菜', '', 5 FROM dual
       UNION ALL SELECT 3, 1, '可乐', 6.00, 3, 'Y', '冰镇可口可乐', '', 1 FROM dual
       UNION ALL SELECT 4, 1, '麻婆豆腐', 18.00, 1, 'Y', '传统川菜，麻辣鲜香', '', 12 FROM dual) s
ON (d.DISHID = s.DISHID)
WHEN NOT MATCHED THEN
  INSERT (DISHID, STOREID, DISHNAME, PRICE, CATEGORYID, ISAVAILABLE, DESCRIPTION, IMAGEURL, ESTIMATEDTIME, CREATETIME, UPDATETIME)
  VALUES (s.DISHID, s.STOREID, s.DISHNAME, s.PRICE, s.CATEGORYID, s.ISAVAILABLE, s.DESCRIPTION, s.IMAGEURL, s.ESTIMATEDTIME, SYSDATE, SYSDATE);

-- 提交事务
COMMIT;

-- 验证数据
SELECT '分类数据:' as INFO FROM dual;
SELECT * FROM PUB.CATEGORY ORDER BY SORTORDER;

SELECT '菜品数据:' as INFO FROM dual;
SELECT DISHID, DISHNAME, PRICE, CATEGORYID, ISAVAILABLE FROM PUB.DISH ORDER BY DISHID;
